name: Docs

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        node-version: [18]
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install ".[docs]"
      - name: Install Node dependencies
        run: |
          cd docs
          npm install
      - name: Compile to html
        run: |
          cd docs
          make html
